import { StyleSheet, Platform } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#1a1a2e',
  },
  tabBar: {
    backgroundColor: '#1a1a2e',
    flexGrow: 0,
  },
  tabBarContent: {
    paddingTop: 4,
    paddingBottom: 4,
    paddingHorizontal: 4,
    gap: 2,
  },
  tab: {
    paddingVertical: 10,
    paddingHorizontal: 14,
    alignItems: 'center',
    borderRadius: 8,
  },
  tabActive: {
    backgroundColor: 'rgba(255,255,255,0.15)',
  },
  tabText: {
    color: 'rgba(255,255,255,0.6)',
    fontSize: 12,
    fontWeight: '600',
  },
  tabTextActive: {
    color: '#fff',
  },
  scroll: {
    padding: 20,
    backgroundColor: '#f5f5f5',
    flexGrow: 1,
  },
  title: {
    fontSize: 28,
    fontWeight: '700',
    color: '#1a1a2e',
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: '#1a1a2e',
    marginBottom: 12,
    marginTop: 8,
  },
  loader: {
    marginTop: 40,
  },
  banner: {
    borderRadius: 12,
    padding: 16,
    marginBottom: 20,
    alignItems: 'center',
  },
  bannerPass: {
    backgroundColor: '#d4edda',
  },
  bannerFail: {
    backgroundColor: '#f8d7da',
  },
  bannerText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#1a1a2e',
  },
  card: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  indicator: {
    fontSize: 18,
    marginRight: 8,
  },
  cardLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1a1a2e',
    marginBottom: 8,
  },
  cardValue: {
    fontSize: 14,
    color: '#444',
    fontFamily: Platform.select({ ios: 'Menlo', android: 'monospace' }),
  },
  input: {
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 8,
    padding: 10,
    fontSize: 14,
    marginBottom: 10,
    fontFamily: Platform.select({ ios: 'Menlo', android: 'monospace' }),
    backgroundColor: '#fafafa',
  },
  radioRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 10,
  },
  radio: {
    paddingHorizontal: 16,
    paddingVertical: 6,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#ccc',
    backgroundColor: '#f9f9f9',
  },
  radioActive: {
    backgroundColor: '#1a1a2e',
    borderColor: '#1a1a2e',
  },
  radioText: {
    fontSize: 13,
    color: '#666',
    fontWeight: '500',
  },
  radioTextActive: {
    color: '#fff',
  },
  button: {
    backgroundColor: '#1a1a2e',
    borderRadius: 8,
    padding: 12,
    alignItems: 'center',
  },
  buttonDanger: {
    backgroundColor: '#c0392b',
  },
  halfButton: {
    flex: 1,
  },
  buttonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
  },
  buttonRow: {
    flexDirection: 'row',
    gap: 8,
  },
  resultText: {
    fontSize: 13,
    color: '#2d6a4f',
    fontFamily: Platform.select({ ios: 'Menlo', android: 'monospace' }),
    marginTop: 10,
    backgroundColor: '#f0fdf4',
    padding: 10,
    borderRadius: 6,
  },
  errorText: {
    fontSize: 13,
    color: '#c0392b',
    fontFamily: Platform.select({ ios: 'Menlo', android: 'monospace' }),
    marginTop: 10,
    backgroundColor: '#fef2f2',
    padding: 10,
    borderRadius: 6,
  },
  resultLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: '#555',
    marginBottom: 4,
  },
  toggleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  checkbox: {
    width: 20,
    height: 20,
    borderRadius: 4,
    borderWidth: 2,
    borderColor: '#ccc',
    marginRight: 8,
  },
  checkboxActive: {
    backgroundColor: '#1a1a2e',
    borderColor: '#1a1a2e',
  },
  toggleLabel: {
    fontSize: 14,
    color: '#444',
  },
  fileListContainer: {
    marginTop: 10,
    backgroundColor: '#f0fdf4',
    padding: 10,
    borderRadius: 6,
  },
  fileItem: {
    fontSize: 12,
    fontFamily: Platform.select({ ios: 'Menlo', android: 'monospace' }),
    color: '#333',
    paddingVertical: 2,
  },
  moreText: {
    fontSize: 12,
    color: '#888',
    fontStyle: 'italic',
    marginTop: 4,
  },
  detectResult: {
    marginTop: 10,
    backgroundColor: '#f0fdf4',
    padding: 10,
    borderRadius: 6,
  },
  detectType: {
    fontSize: 16,
    fontWeight: '700',
    color: '#1a1a2e',
    marginBottom: 6,
  },
  pathLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: '#888',
    marginTop: 6,
  },
  pathValue: {
    fontSize: 11,
    fontFamily: Platform.select({ ios: 'Menlo', android: 'monospace' }),
    color: '#1a1a2e',
    flex: 1,
  },
  copyRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f0f0f0',
    padding: 8,
    borderRadius: 4,
    marginTop: 2,
    gap: 8,
  },
  copyBtn: {
    fontSize: 12,
    fontWeight: '600',
    color: '#fff',
    backgroundColor: '#1a1a2e',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 4,
    overflow: 'hidden',
  },
});
