/**
 * Automatically generated by expo-modules-test-core.
 *
 * This autogenerated file provides a mock for native Expo module,
 * and works out of the box with the expo jest preset.
 *  */

export function getVersion(): string {
  return '1.0.0';
}

export function getGitSha1(): string {
  return 'abc123';
}

export function getGitDate(): string {
  return '2025-01-01';
}

export function getVersionInfo(): { version: string; gitSha1: string; gitDate: string } {
  return {
    version: getVersion(),
    gitSha1: getGitSha1(),
    gitDate: getGitDate(),
  };
}
