/**
 * Automatically generated by expo-modules-test-core.
 *
 * This autogenerated file provides a mock for native Expo module,
 * and works out of the box with the expo jest preset.
 *  */

export type ScrollToParam = any;

export type DomWebViewSource = any;

export type ContentInset = any;

export type ContentInsetAdjustmentBehavior = any;

export async function evalJsForWebViewAsync(
  webViewId: number,
  source: string
): Promise<any> {}

export type ViewProps = {
  source: DomWebViewSource;
  injectedJavaScriptBeforeContentLoaded: string;
  webviewDebuggingEnabled: boolean;
  bounces: boolean;
  decelerationRate: string | number;
  scrollEnabled: boolean;
  pagingEnabled: boolean;
  automaticallyAdjustsScrollIndicatorInsets: boolean;
  contentInset: ContentInset;
  contentInsetAdjustmentBehavior: ContentInsetAdjustmentBehavior;
  directionalLockEnabled: boolean;
  showsHorizontalScrollIndicator: boolean;
  showsVerticalScrollIndicator: boolean;
  onMessage: (event: any) => void;
};

export function View(props: ViewProps) {}
