/**
 * Automatically generated by expo-modules-test-core.
 *
 * This autogenerated file provides a mock for native Expo module,
 * and works out of the box with the expo jest preset.
 *  */

export type Data = any;

export class NativeResponse {
  async startStreaming(response: NativeResponse): Promise<Data | undefined> {
    return;
  }
  async cancelStreaming(
    response: NativeResponse,
    reason: string
  ): Promise<any> {}
  async arrayBuffer(response: NativeResponse): Promise<any> {}
  async text(response: NativeResponse): Promise<any> {}
}

export class NativeRequest {
  async start(
    request: NativeRequest,
    url: URL,
    requestInit: NativeRequestInit,
    requestBody: Data | undefined
  ): Promise<any> {}
  async cancel(request: NativeRequest): Promise<any> {}
}
