/**
 * Automatically generated by expo-modules-test-core.
 *
 * This autogenerated file provides a mock for native Expo module,
 * and works out of the box with the expo jest preset.
 *  */

export type URL = any;

export type FileSystemPath = any;

export type DownloadOptions = any;

export type InfoOptions = any;

export type TypedArray = any;

export type WriteOptions = any;

export type CreateOptions = any;

export const documentDirectory = 0;

export const cacheDirectory = 0;

export const bundleDirectory = 0;

export const appleSharedContainers = 0;

export function info(url: URL): any {}

export async function downloadFileAsync(
  url: URL,
  to: FileSystemPath,
  options: DownloadOptions | undefined
): Promise<any> {}

export async function pickDirectoryAsync(initialUri: URL | undefined): Promise<any> {}

export async function pickFileAsync(
  initialUri: URL | undefined,
  mimeType: string | undefined
): Promise<any> {}

export class FileSystemFile {
  validatePath(file: void): any {}
  textSync(file: void): any {}
  base64Sync(file: void): any {}
  bytesSync(file: void): any {}
  open(file: void): any {}
  info(file: FileSystemFile, options: InfoOptions | undefined): any {}
  write(
    file: FileSystemFile,
    content: string | TypedArray,
    options: WriteOptions | undefined
  ): any {}
  delete(file: void): any {}
  create(file: void, options: CreateOptions | undefined): any {}
  copy(file: void, to: FileSystemPath): any {}
  move(file: void, to: FileSystemPath): any {}
  rename(file: void, newName: string): any {}
  async text(file: void): Promise<any> {}
  async base64(file: void): Promise<any> {}
  async bytes(file: void): Promise<any> {}
}

export class FileSystemFileHandle {
  readBytes(fileHandle: void, bytes: number): any {}
  writeBytes(fileHandle: void, bytes: any): any {}
  close(fileHandle: void): any {}
}

export class FileSystemDirectory {
  info(directory: void): any {}
  validatePath(directory: void): any {}
  delete(directory: void): any {}
  create(directory: void, options: CreateOptions | undefined): any {}
  copy(directory: void, to: FileSystemPath): any {}
  move(directory: void, to: FileSystemPath): any {}
  rename(directory: void, newName: string): any {}
  listAsRecords(directory: void): any {}
  createFile(directory: void, name: string, content: string | undefined): any {}
  createDirectory(directory: void, name: string): any {}
}
