/**
 * Automatically generated by expo-modules-test-core.
 *
 * This autogenerated file provides a mock for native Expo module,
 * and works out of the box with the expo jest preset.
 *  */

export async function callMethod(
  moduleName: string,
  methodName: string,
  arguments: any[]
): Promise<any> {}
