/**
 * Automatically generated by expo-modules-test-core.
 *
 * This autogenerated file provides a mock for native Expo module,
 * and works out of the box with the expo jest preset.
 *  */

export const expoModulesCoreVersion = 0;

export const cacheDir = 0;

export const documentsDir = 0;

export function installOnUIRuntime(): any {}

export function uuidv4(): string {
  return "";
}

export function uuidv5(name: string, namespace: string): string {
  return "";
}

export function getViewConfig(
  moduleName: string,
  viewName: string | undefined
):
  | {
      [key: string]: any;
    }
  | undefined {
  return {};
}

export async function reloadAppAsync(reason: string): Promise<any> {}
